### ISSUE TITLE
Unperspective in .net (C# or VB)

### ISSUE THREAD

**Issue by burnhamcg** [dlemstra/FredsImageMagickScripts.NET#1]
Hello Dirk,

I am writing at the suggestion of Fred who said you might be able to help, possibly as a paid job. We wish to use Fred's 'unperspective' in ,net environment. We are basically dumb VB programmers, but we were able to convert your C# of 'whiteboard' (the closest thing to unperspective we could find) to VB. Our problem is that we need the automatic corner detection that is not in 'whiteboard'. (we looked into this, however the 'Hough' detection, etc. is way beyond our skills)

Basically, our users will be taking a photo (using MS Surface 3) of a standard US paper (215.9 mm x 279.4 mm original image size is 932x720 pix) on a dark desktop. We want to automatically generate a new image of this with corrected perspective as long as four corners are visible and new size is within 10% of original. This is similar to Fred's example with the restaurant receipt. Otherwise, error returns and they must try again with a new photo.

I am hoping you have time to work on this or could recommend someone to do it. 

Kind regards,  Charlie Burnham

**Comment by dlemstra** [comment]
I can assist you by converting Fred his script to .NET and he could license it to you. I will make sure that this will be the next script that I convert to .NET. Not sure if I will be able to help you with the other requirements. I cannot really tell you when I will be able to convert the script but I might give it a look this weekend. I will come back to this issue when the script has been converted.

**Comment by burnhamcg** [comment]
Hi Dirk, I would very much appreciate that. We will certainly license from Fred and also compensate you (if you wish) for this effort. I've attached a typical input test image in case that would be helpful. We did the crop and conversion to greyscale using built-in .net functions. (This is a typical drawing task used in Alzheimer's testing. It does not have too much error because we will encourage users (through rejection of "bad" corner sets) to keep trying until they get something like this as input.)  Kind regards and many thanks, Charlie

**Comment by dlemstra** [comment]
Your e-mail reply that got added as a comment did not include the test image. Can you go to github and add the link there?

**Comment by burnhamcg** [comment]
I think that worked, I dragged it into the reply  box and a large link appeared. Best, Charlie

**Comment by burnhamcg** [comment]
File
![input_gs_720x932](https://cloud.githubusercontent.com/assets/18541217/14721200/2ccc297a-07d3-11e6-91a6-f18efa6a2d5f.jpg)

**Comment by dlemstra** [comment]
It has taken me a couple of days but I am getting close to the end. I have a working prototype now but I will have to clean it up and add unit tests for all the images that Fred has in his examples. Below is the output image I am getting now. You will need to contact Fred for a license once I have published the script. And you can choose some things from my [amazon wish list](http://www.amazon.co.uk/registry/wishlist/1C3TE3001VQZE) if you wish to compensate me for my efforts. I will try to publish the script tomorrow or sometime next week.

![mandril2_p30_t30_out_unperspect_f20_a_t4_s1_s5_b0_r0_el_peak actual](https://cloud.githubusercontent.com/assets/10426229/14938521/6e69dada-0f26-11e6-88b6-074716bf826a.jpg)

**Comment by burnhamcg** [comment]
Thanks, Dirk. I sent you a magic wand. While you were doing that, I tried out a solution using AForge that appeared to work, but not as nice as this. Basically, it makes sure that 4 corners are found AND that they define an area at least 66% of the image space. It finds the corners by assuming that anything below 25% max brightness must be background. Problem is that image needs some brightening and contrast boost and this has to be an adaptive amount. Sort of like (50%) Auto-contrast in Photoshop. (Full auto contrast would be too harsh a filter) The goal is to make it look as much as possible like someone used a hand scanner. Many Thanks, C.

**Comment by dlemstra** [comment]
The script has been published: https://www.nuget.org/packages/FredsImageMagickScripts.Unperspective/.

**Comment by dlemstra** [comment]
I still haven't received your gift. I contacted amazon and asked them for more information but they cannot share that. Can you contact amazon @burnhamcg and ask what is going on with this order?

**Comment by burnhamcg** [comment]
Hi Dirk, My apologies. Apparently they cancelled the order on their own and refunded me some time ago and I missed it. I tried again just now (different item-- game) and we shall see. Best,Charlie

**Comment by dlemstra** [comment]
Thanks for the gift :+1:. Are you aware that you will need to contact Fred Weinhaus when you use it a commercially? He has not heard from you.

**Comment by burnhamcg** [comment]
Hi Dirk, At the moment, we aren't using it because the correction processing  can lead to too much loss of resolution in the original image. (We are limited as to res in the original image to about 1200 x 700.)  I will contact Fred if we incorporate it into a commercial program. Best,Charlie

**Comment by salk52** [comment]
Hi
Could you please provide some sample how to use unperspective script for this scenario?

Thanx
