### ISSUE TITLE
pHash scripts (phashcompare, phashconvert)

### ISSUE THREAD

**Issue by pj-maybe** [dlemstra/FredsImageMagickScripts.NET#10]
Hi there,

Looking for conversion of these excellent scripts.  Magick.NET does not provide a facility to save down image pHash strings... but Fred does!
This is important as can be CPU intensive to run - I want to calculate the hash once then compare with many images.

D

**Comment by dlemstra** [comment]
Have you tried to use the `PerceptualHash` method of `MagickImage`?

**Comment by pj-maybe** [comment]
Holy crap I did not!

That's just what I need!

Sorry to be a bother!

**Comment by dlemstra** [comment]
No problem 👍 I'll close this issue now.
