### ISSUE TITLE
problem with Execute method

### ISSUE THREAD

**Issue by webdevcourse** [dlemstra/FredsImageMagickScripts.NET#11]
Hi,
I need help with the TextCleaner. I have installed imagemagick and textcleaner. 
I have not yet written my code. The text cleaner method Execute give an error CS1503.

Error	CS1503	Argument 1: cannot convert from 'ImageMagick.IMagickImage' to 'ImageMagick.MagickImage'

**Comment by dlemstra** [comment]
It looks like you are trying to call the script with an `IMagickImage` and the versions on NuGet still use `MagickImage` instead. I will publish a new release tonight to resolve this issue. You should also use the latest version of Magick.NET.

**Comment by webdevcourse** [comment]
So where do I get the latest version. Github??



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dlemstra** [comment]
I will publish a new version of TextCleaner tonight and that will most likely solve your issue.

**Comment by dlemstra** [comment]
Can we close this issue @webdevcourse ?

**Comment by webdevcourse** [comment]
did you upload the new version. I took older version of imageMagick so that date of the both match and eventually I have no more errors. I am not using the latest versions now. Nuget still says version 6 months old.

**Comment by dlemstra** [comment]
It turns out I forgot to upload the new version... I just pushed it to the NuGet repository itshould be available withing a couple minutes.

**Comment by webdevcourse** [comment]
Ok thank you. You can close it then.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
