### ISSUE TITLE
Cartoon script returns a grey-scale image

### ISSUE THREAD

**Issue by GiampaLab** [dlemstra/FredsImageMagickScripts.NET#16]
Hi,

I tried to use the Cartoon script in a test project of mine and I noticed that the generated jpg image is always a grey-scale image.
I tried using both .Net Core 2.0 and the full .Net Framework 4.6.1 and Magick.Net-Q16-AnyCPU 7.4.3.

Following the code snippet:
 
```c#
using (var fileStream = new FileStream("TestOutput.jpg", FileMode.Create, FileAccess.Write))
using (var sourceStream = File.OpenRead("TestInput.jpg"))
using (var image = new MagickImage(sourceStream))
{
       CartoonScript cartoonScript = new CartoonScript(CartoonMethod.Method1);
        var processedImage = cartoonScript.Execute(image);
        byte[] bytes = processedImage.ToByteArray();
        fileStream.Write(bytes, 0, bytes.Length);
}
```

Can you please have a look and let me know what I'm doing wrong or if it's a bug?

Thanks,

Giampaolo

**Comment by dlemstra** [comment]
Can you also add a link to your input image?

**Comment by GiampaLab** [comment]
Below you'll find a sample image I tested.

Forgot to mention that I also tried using the [bash script](http://www.fmwconcepts.com/imagemagick/cartoon/index.php) and it's working fine.

![clownfish](https://user-images.githubusercontent.com/10855422/37879988-606e1b78-3079-11e8-851a-3d230f38bb77.jpg)

**Comment by dlemstra** [comment]
I get the following output image:
![test](https://user-images.githubusercontent.com/10426229/37929158-768e9678-313f-11e8-96a1-1fd5437908a6.jpg)

Are you sure you are not doing anything else?

p.s. You should also dispose the processedImage.

**Comment by GiampaLab** [comment]
Thanks for the advice I changed my code to dispose the processed image too but I still  get the same result.

I guess you pretty much copied and pasted my sample code?
If that's the case it's not clear to me why I'm getting a different result.

Attached you'll find a zip file with my test solution project can you please give it a try?


Thanks in advance!

[CartoonEffectTestFullFramework.zip](https://github.com/dlemstra/FredsImageMagickScripts.NET/files/1853208/CartoonEffectTestFullFramework.zip)

**Comment by dlemstra** [comment]
This turned out to be an OpenCL issue. I just pushed a patch to the ImageMagick repository to resolve this. This will be fixed in the next release of Magick.NET that should be released within one week. You can for now use `OpenCL.IsEnabled=false` to disable OpenCL for now.

**Comment by GiampaLab** [comment]
Hi @dlemstra ,

Glad you found the issue and that you managed to fix it!

I will apply the suggested setting and test it again soon, also I will try the new Magick.NET release as soon as it is available to make sure the problem is fixed.

Don't know much about OpenCL so my next question are: 

- Will this setting have a performance impact?
- Are there any real scenarios for which you would turn this setting to false?

I know the one you suggested is just a temporary workaround I'm being curious here...

**Comment by dlemstra** [comment]
With OpenCL enabled you will offload some work to the GPU and this will happen asynchronous. Once the ImageMagick library needs the pixels again in non GPU code it will do an "await" on the GPU. 

In some situations you can benefit from this but in other situations it might not be that helpful. But the first time the GPU is used on a machine there will be a benchmark to determine if it will be better to use the GPU or the CPU. I think you would turn this setting off when you are running Magick.NET in a web application. Your machine probably does not have a GPU so you don't want the benchmark penalty when you run the application for the first time. But when you run this on a desktop you can probably benefit from offloading some of the work to the GPU. Short answer: it depends.

I will leave this issue open so you can confirm this has been fixed when I publish the next release.

**Comment by GiampaLab** [comment]
Hi @dlemstra , I just tested the new release and it's working correctly, you can close this bug.

Thanks for the support and for the detailed explanation really informative!
