### ISSUE TITLE
Regarding parameter values

### ISSUE THREAD

**Issue by ervaibhavkumar** [dlemstra/FredsImageMagickScripts.NET#20]
Hi,

I want to know that what would be optimal set of parameters and parameter values that needs to be used in order to get good image.

Regards
Vaibhav

**Comment by dlemstra** [comment]
I have no idea what you are asking? I am missing some kind of context?

**Comment by ervaibhavkumar** [comment]
When we run the script 
./textcleaner [optional parameters] input_file output_file

what would be the optimal value for the optional parameters in order to get good quality image having text in it.

**Comment by dlemstra** [comment]
It looks like you are asking the question in the wrong place? This is a C# library that has the scripts of Fred translated into C#. If you want to ask questions about the script you can do that here: https://imagemagick.org/discourse-server/viewforum.php?f=26?
