### ISSUE TITLE
Autotrim nuspec is missing a file

### ISSUE THREAD

**Issue by OldNo7** [dlemstra/FredsImageMagickScripts.NET#9]
`Publish/Nuspec/FredsImageMagickScripts.Autotrim.nuspec`  should also include `..\..\src\FredsImageMagickScripts.NET\Geometry\Autotrim\Line.cs`

**Comment by dlemstra** [comment]
Thanks for reporting this. It appears I made a mistake when I added StyleCop to this project. Will publish a new release very soon to resolve this.

**Comment by dlemstra** [comment]
I just pushed a new version of the package to resolve this.
